### ISSUE TITLE
opnsense fails to bring up pfatt interface on boot

### ISSUE THREAD

**Issue by briangordon** [MonkWho/pfatt#10]
Whenever I reboot my firewall, the WAN interface fails to come up. From `/var/log/pfatt.log`:

```
2020-06-05 21:37:53 :: [pfatt.sh] :: building netgraph nodes...
2020-06-05 21:37:53 :: [pfatt.sh] ::   creating ng_one2many... OK!
2020-06-05 21:37:53 :: [pfatt.sh] ::   creating vlan node and interface... OK!
2020-06-05 21:37:53 :: [pfatt.sh] ::   defining etf for bge1 (ONT)... OK!
2020-06-05 21:37:53 :: [pfatt.sh] ::   defining etf for ue0 (RG)... ngctl: send msg: No such file or directory
```

I guess the USB fast ethernet adapter isn't available yet when the `/usr/local/etc/rc.syshook.d/early/` scripts run. Unfortunately if I move the pfatt script to the `start` directory then the firewall comes up with the wrong interface assigned to WAN. 

If I put the pfatt script into the `early` directory then it partially runs until failure and I can SSH into the firewall and re-run the pfatt script manually. This works fine but it's hardly an ideal solution.

I'm using [the exact ethernet adapter recommended in the readme](https://www.amazon.com/gp/product/B00007IFED), on an older (c. 2012) Dell PowerEdge server, running opnsense 19.7.10. 

Has anyone else had this issue? If others have had this same problem then it might make sense to revise the README.

**Comment by Watanuki-kun** [comment]
I know that in general, usb network adapters are a bit finicky. If your guess is right, it might just be a timing issue. Have you tried to putting in a boot delay to see if the nic needs more time to be visible/initialize?

**Comment by maxfield-allison** [comment]
You should be using the opnatt.sh script, not the pfatt.sh script

**Comment by briangordon** [comment]
> You should be using the opnatt.sh script, not the pfatt.sh script

I first set up the pfatt script before openatt.sh was split off, and I don't see anything that would make a difference. The old script had a variable for switching between opnsense and pfsense.

**Comment by briangordon** [comment]
Yes, that's the directory (and file name) where I've put the pfatt script. And I'm sure that the right modules are loaded; I suspect that it's just the interface that's not available yet when the `early` scripts run.

Thanks for your help though.

**Comment by MonkWho** [comment]
I saw previously that someone had success running the script in /early if they named it 99-opnatt.sh. I believe that made it execute last but I don't know if they were using a USB NIC or not.

You might also want to look into a supplicant mode if your ATT RG is one of the easily rootable models like BGW210. This method eliminates a need for a secondary NIC and you can put your RG away completely.

**Comment by MonkWho** [comment]
There hasn't been any activity in this thread for a while so I'm going to go ahead and close the issue.
