### ISSUE TITLE
Enabling DHCPv6 on WAN causes intermittent IPv4 timeouts

### ISSUE THREAD

**Issue by maxfield-allison** [MonkWho/pfatt#13]
When I enable DHCPv6 on the WAN interface, My IPv4 connection drops every 30 or so seconds. It eventually comes back up but the behavior persists. The WAN interface does not pull an IPv6 address. I'm using the opnatt script on OPNsense 20.1.7

**Comment by MonkWho** [comment]
This is very strange and I honestly have no idea why it would be behaving this way. I don't use IPv6 but have you looked at the specific instructions in the readme related to IPv6 stuff?

**Comment by BradenM** [comment]
I also ran into this issue. Have not had time to do some through debugging, so had to disable it for now. :shrug:

**Comment by MonkWho** [comment]
@maxfield-allison and @BradenM 
Have you guys had any luck with additional tests? It would be good to add more details for other people that might encounter similar issues with IPv6.

**Comment by maxfield-allison** [comment]
I haven't had time lately but I still fully intend to take a solid stab at everything once life calms down a bit.

**Comment by dkowis** [comment]
I am using pfatt on 20.1, and I do have dhcp6 on the wan enabled. I have had exactly zero problems.... 

I'm about to update it to 20.7, since 20.1 is now EoL ( https://butt.holdings )
![image](https://user-images.githubusercontent.com/28048/94353905-b2564200-003b-11eb-96e8-b5f8407c5824.png)

**Comment by maxfield-allison** [comment]
lol 
![image](https://user-images.githubusercontent.com/42394355/94468116-8d6fe500-0189-11eb-9fa0-ce06071b3f50.png)

**Comment by maxfield-allison** [comment]
@dkowis can you share your dhcpv6 client config?

**Comment by dkowis** [comment]
I don't run dhcpv6 relay or otherwise, it does the track interface. This is the LAN configuration:
![image](https://user-images.githubusercontent.com/28048/94473919-dc724600-019a-11eb-8f2e-657c2a785269.png)

Here's the WAN configuration for dhcp6:
![image](https://user-images.githubusercontent.com/28048/94474000-fc096e80-019a-11eb-9086-d8461fbdbf8e.png)

**Comment by maxfield-allison** [comment]
After updating and running healthchecks, installing the netmap kernel and redoing the script and instal, I'm happy to say that dhcpv6 is working and bypass is functioning as it should. I'm guessing something got twisted up when I updated to 20.7 and by redoing all of it manually in the CLI the script was able to function correctly once more.
