### ISSUE TITLE
Internet connection dies after X hours

### ISSUE THREAD

**Issue by mnd31** [MonkWho/pfatt#14]
Hi!

Love this solution, thank you!

After what seems to be about 24 hours my internet connection drops, requiring a reboot of pfsense. Reboot fixes the issue perfectly and no further action is needed. Sometimes it drops out within an hour, though, but most times it's fine for almost a day.

I took a look at my pfatt.logs and don't see any information after the successful setup of each session right after reboot.

Is there a particular log that would help investigate this?

I'm running the following:

2.4.5-RELEASE-p1 (amd64)
built on Tue Jun 02 17:51:17 EDT 2020
FreeBSD 11.3-STABLE

AMD A4-5050 APU with Radeon(TM) HD Graphics
4 CPUs: 1 package(s) x 4 core(s)
AES-NI CPU Crypto: Yes (inactive)

Thanks!

**Comment by maxfield-allison** [comment]
Are you managing the created interfaces within PFsense GUI? What other services are you running (e.g. IPS/IDS, Vlans, etc.)?

**Comment by maxfield-allison** [comment]
As far as logs go, I'm on OPNsense but the equivalent of System: Log Files: General should allow you to search entries containing "ngeth" which will show you the system activity for the virtual interface.
![image](https://user-images.githubusercontent.com/42394355/86980725-3fc77b80-c14a-11ea-9ad1-acd933f2ee1f.png)

**Comment by mnd31** [comment]
Apologies for the late reply, I had to revert my pfsense box because I needed a stable internet connection for WFH this week and next. I'll try again in 2 weeks. I'm ok if you want to resolve this, if it happens again I'll open a new issue with the logging. I have a feeling it'll work better with a clean install.

Just for completeness sake.. the only interface the GUI was managing was the LAN, and the only other service if i remember correctly was openVPN.

**Comment by maxfield-allison** [comment]
I'd just leave it pending. Interested to find out if a fresh install fixes the issue.

**Comment by dkowis** [comment]
If it matters, or helps any, I've had this up on OpnSense for months now, zero problems.
![image](https://user-images.githubusercontent.com/28048/88820543-0dc49a80-d187-11ea-8190-1e4ff7699527.png)

**Comment by MonkWho** [comment]
@mnd31 have you had a chance to poke at it some more? I am interested to see what was causing this and if it's something we should add to the readme.

**Comment by mnd31** [comment]
Funny timing, I just got it set back up after a clean install. Will watch it to see if it happens again.

**Comment by mnd31** [comment]
Zero problems after 22 days. I think a fresh install fixed it. Thanks!
