### ISSUE TITLE
Fix spelling of maintain in repo description

### ISSUE THREAD

**Issue by lilchancep** [MonkWho/pfatt#15]
enable true bridge mode for AT&T U-Verse and pfSense (this is a fork of an original repository https://github.com/aus/pfatt. Since it is not available anymore, I'll do my best to maitain a copy for people that still need a bypass)

Enable true bridge mode for AT&T U-Verse and pfSense (this is a fork of an original repository https://github.com/aus/pfatt. Since it is not available anymore, I'll do my best to maintain a copy for people that still need a bypass)

**I appreciate this repo so much, thank you MonkWho**

**Comment by MonkWho** [comment]
Done. Thank you for fixing my typos.
