### ISSUE TITLE
ng_etf.ko may not be included in netgate hardware specific builds of PFSense

### ISSUE THREAD

**Issue by ReignBock** [MonkWho/pfatt#21]
In PFSense build 2.4.5-p1 for Netgate hardware SG-4860 Desktop, ng_etf.ko is not included and a manual install of the Kernel Module is necessary. I recommend putting a caveat in the ng_etf section that netgate appliances may not have ng_etf.ko even on the latest version.

**Comment by maxfield-allison** [comment]
I know this is small potatoes but you could fork, edit, and pull request the changes to the readme for MonkWho.

**Comment by ReignBock** [comment]
thanks @maxfield-allison I'll give it a shot. I'm still new to github so I didn't know what the proper way to add this change was.

**Comment by ReignBock** [comment]
modifed README.md and created pull request #26

**Comment by MonkWho** [comment]
I was under impression from this https://redmine.pfsense.org/issues/10463 that they added ng_etf.ko in 2.4.5-p1 for all builds. Looks like some hardware is still missing it. Thank you for letting us know.
