### ISSUE TITLE
Has anyone tried 2.5.x with the supplicant method?

### ISSUE THREAD

**Issue by bigjohns97** [MonkWho/pfatt#22]
Just wondering if anyone has tried the 2.5.x version of PfSense with the supplicant method, thinking of trying it out this weekend.

**Comment by MonkWho** [comment]
Pfatt scripts have not been tested on pfsense 2.5.x. If you do end up testing please let us know if you encounter any issues.

**Comment by bigjohns97** [comment]
I ended upgrading and haven't come across any issues yet.

**Comment by MonkWho** [comment]
Excellent news. Are you using a traditional bypass with your RG still hooked up or are you using a supplicant method?

**Comment by bigjohns97** [comment]
Supplicant, kernel module was already present.

Original install was from a 2.4.5 - updated to p1 through GUI, and then to 2.5.0 through GUI as well.

PfblockerNG did require a uninstall and reinstall but everything else worked out of the box. *I am running a beta version of pfb*

**Comment by MonkWho** [comment]
Perfect. Thank you for providing additional details.
