### ISSUE TITLE
Could you run this in front of another router?

### ISSUE THREAD

**Issue by MatthewGCampbell** [MonkWho/pfatt#27]
Currently have a UDM Pro which can only do basic routing, so I bought a Pfsense box to go infront of it to do management of another network currently have the two separate routers on two different public IPs, any way I could pass static addresses and get IPv6 on my routers in front of the Pfsense box, I haven’t got mine yet to test. Just wondering if anyone else has a config like this.

**Comment by MonkWho** [comment]
I haven't seen anyone mention configs like this. Better place to check would probably be netgate forums.

**Comment by MatthewGCampbell** [comment]
Not much their either, everything works except for my IPv6 I can’t get the prefix to the other router. WAN gets the /60 then I want my other router to get a /64 but it just doesn’t.
