### ISSUE TITLE
Request more noob friendly instruction for ipv6 Prefix Delegation

### ISSUE THREAD

**Issue by lilchancep** [MonkWho/pfatt#29]
Under the IPV6 Section it has 

DHCPv6 Server & RA

Go to Services > DHCPv6 Server & RA
Enable DHCPv6 server on interface LAN
Configure a range of ::0001 to ::ffff:ffff:ffff:fffe
Configure a Prefix Delegation Range to 64
Save
Go to the Router Advertisements tab
Configure Router mode as Stateless DHCP
Save

The part I just literally cannot understand is the
**Configure a Prefix Delegation Range to 64**

Would It be possible to just add the **From** and **To** Values to the guide?

**Comment by AndrewReaganM** [comment]
Have you tried leaving `Prefix Delegation Range` blank and setting `Prefix Delegation Size` to 64? That is how mine is set up, but looking back not because I understood the directions. I suppose that was a mistake that I made, but my config works... It might be just supposed to say `Prefix Delegation Size` in the instructions. Can anyone else weigh in on this?

**Comment by lilchancep** [comment]
> Have you tried leaving `Prefix Delegation Range` blank and setting `Prefix Delegation Size` to 64? That is how mine is set up, but looking back not because I understood the directions. I suppose that was a mistake that I made, but my config works... It might be just supposed to say `Prefix Delegation Size` in the instructions. Can anyone else weigh in on this?
> 
> edit: it looks like `Prefix Delegation Range` isn't necessary unless you would like to delegate prefixes to the LAN, and for a home router you probably just want to serve out addresses. I am quite certain that the README should say `Prefix Delegation Size`.
> 
> https://forum.netgate.com/topic/113550/solved-lan-ipv6-clients-not-getting-pfsense-lan-ipv6-tracked-ip-for-dnsforward/9

Wow, i never tried to just leave it blank. That would of helped me not bang my head against the wall for hours.

**Comment by MonkWho** [comment]
Thank you for putting together a pull request @AndrewReaganM. Hope this helps more people configure their IPv6 stuff.
