### ISSUE TITLE
Unable to ping IPV6 Addresses from pfsense but can on LAN

### ISSUE THREAD

**Issue by lilchancep** [MonkWho/pfatt#30]
I do not know if a lot of people are running into this issue.  I do know that this issue makes updating/installing packages a pain as it just hangs for a long time.

[This is what I have come accross](https://forum.netgate.com/topic/156585/pfsense-box-cannot-access-anything-over-ipv6-lan-clients-can/3)

Making this change allows the router to actually access ipv6 and all issues with updating/package manger stop.

**"On WAN interface check "Only request an IPv6 prefix, do not request an IPv6 address".
ATT doesn't provide a routable IP to the interface."** 

Anyone else have thoughts on this?

**Comment by AndrewReaganM** [comment]
Hey! Its Netgate Forum me! I noticed it because I couldn't access IPv6 DNS servers. I think this might should be added to the docs. @MonkWho ?

**Comment by MonkWho** [comment]
Looks good. Thank you @AndrewReaganM.
