### ISSUE TITLE
Change DNS

### ISSUE THREAD

**Issue by MatthewGCampbell** [MonkWho/pfatt#35]
Is it possible to change the DNS on pfsense to like 1.1.1.1 while running this? Whenever I go to **System > General Setup > DNS Servers > change it to 1.1.1.1 and 1.0.0.1 > and add IPv6 2606:4700:4700::1111 and 2606:4700:4700::1001**. 
Is this possible to do or do you need to have AT&Ts DNS in there for it to work, it seems to break my WAN when I do that.

**Comment by MonkWho** [comment]
I don't have IPv6 set up so I can't comment on that part. But for regular DNS I have Cloudflare IPs entered and it works perfectly fine.

**Comment by MatthewGCampbell** [comment]
Where did you enter it?

**Comment by MatthewGCampbell** [comment]
and did you uncheck **Allow DNS server list to be overridden by DHCP/PPP on WAN**?

**Comment by MonkWho** [comment]
Cloudflare IPs entered in System -> General Setup -> DNS Server Settings. And "Allow DNS server list to be overridden by DHCP/PPP on WAN" is unchecked.

**Comment by MatthewGCampbell** [comment]
And did you choose a gateway? WAN_DHCP for both? Or did you leave that empty?

**Comment by MonkWho** [comment]
Gateway selector can be left to "none" unless you want to have different DNS servers set for different WAN interfaces.

**Comment by owenthewizard** [comment]
I also concur that you can use any DNS you like with pfatt, just like regular pfsense.

**Comment by MatthewGCampbell** [comment]
Unsure what the issue was previously, maybe i forgot to reset the state tables, really weird but now it works.
