### ISSUE TITLE
Does ATT actually route you your IPv6 address?

### ISSUE THREAD

**Issue by MatthewGCampbell** [MonkWho/pfatt#36]
Having issues with IPv6, cause it doesn't seem that AT&T routes me my IPv6 WAN address, anyone else have a similar issue?

**Comment by maxfield-allison** [comment]
Att doesn't seem to assign a routable ipv6 address to the wan adapter with this setup. That said, every other interface and client should be able to get one. I had it functioning well but pulled the plug in ipv6 on my network until I can find time to get pihole etc working.

**Comment by AndrewReaganM** [comment]
Have you tried enabling Request only an IPv6 prefix?

**Comment by MatthewGCampbell** [comment]
I was having issues with prefix delegation from pfsense to a router behind it and forgot to have the WAN set to get a prefix from AT&T (kinda stupid of me) but I finally figured it out, if you need any help I might be of assistance.

>

**Comment by dkowis** [comment]
Yes. I have an ATT ipv6 address. IIRC it took some time for it to percolate through.

My WAN configuration:
![image](https://user-images.githubusercontent.com/28048/97338817-cf0ab300-184f-11eb-930f-07a057b34d19.png)

My LAN configuration:
![image](https://user-images.githubusercontent.com/28048/97338868-dfbb2900-184f-11eb-8796-f69c474de9e1.png)

**Comment by MatthewGCampbell** [comment]
Didn’t have the request prefix box checked cause I thought they actually gave you an address.

Thanks

>

**Comment by maxfield-allison** [comment]
FYI I've unchecked the prefix only box and received a gateway and IP outside of the prefix subnet. not sure what this means for us since OPNsense ipv6 is being testy as of late but thought i'd share

**Comment by MatthewGCampbell** [comment]
Very interesting, I will now be testing this further, but when I had it unchecked for me AT&T wouldn’t actually route the IP to me.

Thanks, Matthew
