### ISSUE TITLE
Anyone tested OPNSense 21.1? 

### ISSUE THREAD

**Issue by drewmullen** [MonkWho/pfatt#46]
has anyone tested more recent versions of OPNSense? I'm on 20.1... nervous to update if it breaks bridge mode

https://www.reddit.com/r/OPNsenseFirewall/comments/l6xgl2/opnsense_211_marvelous_meerkat_released/

**Comment by Aerowinder** [comment]
Tread carefully on FreeBSD 12. If you were already using it with no problems, you should be OK. But as always, make a backup just in case.

**Comment by cspencer49519** [comment]
I just installed it tonight. I'm using the wpa supplicant method. Upgrade went fine and everything seems to be working. I'll give it 48 hours and try to report back.

**Comment by cspencer49519** [comment]
Been running strong for a couple days now, no problems. I'll be staying on this version.

**Comment by drewmullen** [comment]
thanks @cspencer49519
