### ISSUE TITLE
2.4.5 and ng_etf on ARM processors

### ISSUE THREAD

**Issue by tyler-8** [MonkWho/pfatt#6]
Per this issue https://redmine.pfsense.org/issues/10463 - ng_etf is not available to pfSense running on ARM processors. 2.4.5-p1 is when it will be fixed. Until then, you'll have to build that module for yourself using the 'legacy' way.

**Comment by MonkWho** [comment]
Oh yeah I forgot to add the note to the readme to mention it. Thank you for catching it.

**Comment by Prodian0013** [comment]
@tyler-8 so after 2.4.5-p1 pfatt should all work with the Netgate SG-1100?  I dont one have just been looking at getting one but only if pfatt method works with it.

**Comment by MonkWho** [comment]
@Prodian0013 currently according to that bug report they are planning to add ng_etf in 2.4.5-p1. Unfortunately it's not guaranteed so we can't say for sure. Once it's added you should be able to run this bypass on any hardware and not just amd64 architecture based ones.

If you want it now you can look into running a VM of FreeBSD 11.3 and copying ng_etf it from there.
