### ISSUE TITLE
PFSense 2.5.1 Netgraph issues

### ISSUE THREAD

**Issue by smplman** [MonkWho/pfatt#64]
I'm running into some issues with running the script in `supplicant` mode. When the script tries to create the vlan and `ngeth0` interface all of the `ngctl` calls come back with `ngctl: send msg: No such file or directory`. My `ONT_IF` is set to `em1` as that is the port that I have the ONT Interface connected to. Both `RG_ETHER_ADDR` and  `EAP_SUPPLICANT_IDENTITY` are set and I don't think those are the issue. I'm not sure if this is a `2.5.1` issue as I have seen posts about people getting this to work.

Here is where those `ngctl` calls start being made..
https://github.com/MonkWho/pfatt/blob/supplicant/bin/pfatt.sh#L147
```
  /usr/sbin/ngctl mkpeer $ONT_IF: vlan lower downstream
  /usr/sbin/ngctl name $ONT_IF:lower vlan0
  /usr/sbin/ngctl mkpeer vlan0: eiface vlan0 ether
  /usr/sbin/ngctl msg vlan0: 'addfilter { vlan=0 hook="vlan0" }'
  /usr/sbin/ngctl msg ngeth0: set $RG_ETHER_ADDR
```

I'm pretty new to the BSD space, but pretty well versed in unix. I suspect there is something simple that i'm missing and running a google search for the errors didn't help me much. I have wpa_supplicant working on my EdgeRoute X. This is for a new PFSense box that I just built. Any help would be appreciated.

**Comment by smplman** [comment]
I was able to fix this and get a WAN ip by adding the code below before the lines I mentioned above.
```
/usr/local/bin/php -r "pfSense_ngctl_attach('.', '$ONT_IF');"
```
I found that reading through this forum post https://forum.netgate.com/topic/99190/att-uverse-rg-bypass-0-2-btc/303?lang=en-US

My next issue is the speed. I have only been getting like 400 down and 150 up. On my ERX i'm getting around 800 down and up. I'm also working through the readme to get a public IPv6 address, not sure if it's related to the speed issue. I didn't have to do anything special on the ERX to get an IPV6 address.

**Comment by zombielinux** [comment]
Let me know if you figure out the IPV6 address. I'm not getting a default route on opnsense, and manually adding the correct one still doesn't give WAN access.

**Comment by smplman** [comment]
@zombielinux I think i'm going to try out OpnSense over the weekend. I will report back with my findings.

**Comment by A-vesalius** [comment]
FYI, OPNsense is about to release 22.1, currently on RC2 and final maybe in a week or 2 switching to FreeBSD 13 as the base, and this will undoubtedly result in a new set of issues on the AT&T bypass front.

**Comment by smplman** [comment]
Tracking 22.1 over here https://github.com/MonkWho/pfatt/issues/65#issuecomment-1025294502

**Comment by zombielinux** [comment]
To all reporting it not working. 

When you manually run the script, where does it fail?
