### ISSUE TITLE
BGW320?

### ISSUE THREAD

**Issue by PerennialWheat** [MonkWho/pfatt#68]
Any news about this working on the BGW320 or anything? I'm going to get at&t fiber soon (only good service around).

**Comment by maxfield-allison** [comment]
there isnt currently any bypass for the 320. That said I went from a bypass on the older model to no bypass on the 320 and i've had no issues. the 320 also has a 5gbe so you can get your full overprovisioned line rates if you have compatible hardware on the other end.

**Comment by PerennialWheat** [comment]
> there isnt currently any bypass for the 320. That said I went from a bypass on the older model to no bypass on the 320 and i've had no issues. the 320 also has a 5gbe so you can get your full overprovisioned line rates if you have compatible hardware on the other end.

Oh that's great! thanks for the information 🙂

**Comment by mcmar** [comment]
I don't think what @maxfield-allison said is true. You can find plenty of people complaining that the 320 drops your speed in IP passthrough mode when you try to use it with another router. If you plan to use it as your only router, then it's plenty fast and the wifi is great, but you lose any ability to do things like hairpin NAT or add your own DNS resolver.
https://www.reddit.com/r/PFSENSE/comments/nyyrea/my_att_gigabit_fiber_bgw320500_ip_passthru/

**Comment by maxfield-allison** [comment]
I'm speaking from personal experience. I checked your link and I don't see anyone complaining about not reaching line speeds in passthrough. I want to note that I'm still using opnsense behind the 320 and swapped over to a public subnet range (for other reasons obviously) so I don't use passthrough.

**Comment by PerennialWheat** [comment]
> I don't think what @maxfield-allison said is true. You can find plenty of people complaining that the 320 drops your speed in IP passthrough mode when you try to use it with another router. If you plan to use it as your only router, then it's plenty fast and the wifi is great, but you lose any ability to do things like hairpin NAT or add your own DNS resolver. https://www.reddit.com/r/PFSENSE/comments/nyyrea/my_att_gigabit_fiber_bgw320500_ip_passthru/

Nope max is correct, I'm reaching my full line speeds with IP passthrough. I can also use my own dns resolver

**Comment by maxfield-allison** [comment]
good to hear its still working well for you! I'm still digging around here and there to find some way around the 320. There was recently some talk of a new Nokia ONT that we may be able to use. Thanks to both of you for the reminder to check back up with that!

**Comment by PerennialWheat** [comment]
> good to hear its still working well for you! I'm still digging around here and there to find some way around the 320. There was recently some talk of a new Nokia ONT that we may be able to use. Thanks to both of you for the reminder to check back up with that!

Yep I heard of something with cloning the ont or sfp module. There's also a hardware root method to extract certificates from the bgw320 But you still need an external ont.
