### ISSUE TITLE
Does the bypass work with XGS-PON if you have a BGW210?

### ISSUE THREAD

**Issue by PerennialWheat** [MonkWho/pfatt#71]

**Comment by maxfield-allison** [comment]
I think it does but you have to use the supplicant mode and have the certificates from the device. easy enough to try both? also, curious how you know you have xgs? recent 5Gb upgrade? I would have thought theyd require to swap in their newer gateway for that service.

**Comment by PerennialWheat** [comment]
> I think it does but you have to use the supplicant mode and have the certificates from the device. easy enough to try both? also, curious how you know you have xgs? recent 5Gb upgrade? I would have thought theyd require to swap in their newer gateway for that service.

5gb is available in my area and I have a newer black ont. I got the bgw 210 by calling at&t and requesting for it.

**Comment by maxfield-allison** [comment]
the new ONT is news to me. I'd say give it a shot and let us know how it goes, ya know... for science!

**Comment by PerennialWheat** [comment]
> the new ONT is news to me. I'd say give it a shot and let us know how it goes, ya know... for science!

doesn't hurt to try I guess (expect my wallet as I don't have pfsense hardware yet)

**Comment by maxfield-allison** [comment]
good news is you can get a solid box for less than 100 bucks. tons of older celeron processors work just fine, throw in a cheap 2 port nic, and off you go.
