### ISSUE TITLE
wpa_supplicant method with opnsense

### ISSUE THREAD

**Issue by sonoseco** [MonkWho/pfatt#8]
I noticed the proxy method with the RG was updated for opnsense, thank you @MonkWho! I've been using the wpa_supplicant version with pfsense for a while but I'm switching to opnsense and was wondering if the `pfatt.sh ` script would be the same?

**Comment by MonkWho** [comment]
I looked the scripts over and created a version of supplicant opnatt.sh here - https://github.com/MonkWho/pfatt/blob/supplicant_OPNsense_testing/bin/opnatt.sh

Unfortunately I don't have OPNsense so I can't test it. Try it out and let me know if it works for you.

**Comment by sonoseco** [comment]
Thank you for editing the script @MonkWho. I added it to my installation of OPNsense and it is working, just needed to add the script to `/usr/local/etc/rc.syshook.d/early` as `99-opnatt.sh`, and copy the `wpa` folder to `/conf/pfatt`.

**Comment by Watanuki-kun** [comment]
Tried out the supplicant version and it is working for me also.
