### ISSUE TITLE
Is there a way to get the wireless on the RG working?

### ISSUE THREAD

**Issue by nunziotocci** [MonkWho/pfatt#85]
I've bypassed by BGW210, but it would be nice to be able to use it for the Wi-Fi.

If not I can just buy a Wi-Fi card for my bypass box. Just checking to see if I can avoid that expense and complexity. I've rolled my own firewall/NAT with FreeBSD+IPFW+In Kernel NAT so I can't just add another interface like in pfSense, I need to figure out the rules.

**Comment by owenthewizard** [comment]
You could try and plug in the RG to your network on one of the LAN ports, not sure if that would work though.
Only the EAP frames are sent via the bridge, so it definitely wouldn't work that way.
Why not just setup separate wireless AP? That would be a lot better than using a Wi-Fi card in your bypass box.

**Comment by nunziotocci** [comment]
If nobody else has used the RG as the Wi-FI AP, then I'll do something else. Just wanted to check before spending any money on something else.
